#!/bin/bash
# My monitoring script; you would probably want to rewrite the site-specific
# stuff below.

cd "$(dirname "$0")"
git pull >&/dev/null

outfile=$1

exec >"$outfile.tmp"

for thing in ok info warning problem; do
  eval "$thing() { echo \"<div class='$thing'>\$1</div>\"; }"
done

check_disk() {
  local name=$1
  local limit=$2
  local bad_deadness=$3
  local good_deadness=$4
  local df_output=$5

  local usage=`echo "$df_output" | tail -n1 | awk '{print $5}'`
  if (( ${usage%%%} > $limit )); then
    $bad_deadness "$name is at $usage (limit = $limit%)"
  else
    $good_deadness "$name is at $usage"
  fi
}

host_up_check() {
  local name=$1
  local ip=$2
  local howbad=$3

  ping -c 2 -q $ip > /dev/null || { $howbad "$name is offline"; return; }
  ssh $ip :                    || { $howbad "$name SSH is down"; return; }

  check_disk "$name root FS" 90 problem info "`ssh $ip df /`"
  ok "$name is online"
}

vpn_ping_check() {
  local name=$1
  local ip=$2

  if ping -c 2 -q $ip > /dev/null; then
    ok "VPN client $name is connected"
  else
    warning "VPN client $name is offline"
  fi
}

echo "<div id='rundate'>`date +%s`</div>"

host_up_check rorschach  10.35.0.2 problem
host_up_check reykjavik  10.35.0.3 problem
host_up_check rho        10.35.0.4 problem
host_up_check rockhopper 10.35.0.5 info         # not always on

# Check gitlab server
if ! curl 10.35.0.3:8180 >&/dev/null; then
  problem "reykjavik gitlab appears to be down"
else
  ok "reykjavik gitlab is running"
fi

# Check RAID6 on rho
ssh 10.35.0.4 'cat /proc/mdstat' | egrep -q UUUUUUUUUUUU \
  || problem "rho RAID6 is degraded or down"

# Make sure /mnt/v1 is mounted and writable
if ! [[ -d /mnt/v1/st ]]; then
  problem "/mnt/v1 is offline"
else
  touch /mnt/v1/st/deadjim || problem "/mnt/v1 isn't writable"
fi

# shared volumes
check_disk "/mnt/v1" 90 problem info "`df /mnt/v1`"
check_disk "reykjavik /mnt/t9" 90 problem info "`ssh 10.35.0.3 df /mnt/t9`"
check_disk "reykjavik /mnt/t3" 90 problem info "`ssh 10.35.0.3 df /mnt/t3`"

mv "$outfile.tmp" "$outfile"

# VPN clients
vpn_ping_check iniidae      10.35.1.4
vpn_ping_check iris         10.35.1.6
vpn_ping_check lily         10.35.1.8
vpn_ping_check xhosacetus   10.35.0.10
vpn_ping_check xenorophidae 10.35.0.12
